kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ include "dummy-app.fullname" . }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ include "dummy-app.fullname" . }}"
    env: "{{ .Values.env }}"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: "{{ include "dummy-app.fullname" . }}"
      env: "{{ .Values.env }}"
  template:
    metadata:
      name: "{{ include "dummy-app.fullname" . }}"
      labels:
        app: "{{ include "dummy-app.fullname" . }}"
        env: "{{ .Values.env }}"
    spec:
      containers:
      - name: "{{ include "dummy-app.fullname" . }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 25
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        {{- if .Values.resources }}
        resources:
        {{- toYaml .Values.resources | nindent 10 }}
        {{- end }} 
