apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ include "dummy-app.fullname" . }}-ingress"
spec:
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ include "dummy-app.fullname" . }}-service"
            port:
              number: 80
  ingressClassName: nginx
